### ISSUE TITLE
Striping leading and trailing whitespace in status-right and status-left

### ISSUE THREAD

**Issue by nunoh** [tmux-plugins/tmux-battery#11]
I noticed this bug when trying to use a space for padding in either sides of the tmux status bar, so that the time and session name don't look so "squashed" against the side of the screen.

If I have something like `set -g status-left  '       [#S]'` and this plugin's enabled, the leading whitespace gets stripped, whereas if I don't include it in the plugins list I get the proper spacing. The same happens for `status-right`.

**Comment by bruno-** [comment]
Thanks for reporting, I wasn't aware of this. The issue should be fixed now.

I'd appreciate if you could update the plugin, see if things work and let me know. Thanks.

**Comment by nunoh** [comment]
It works! Thanks. :bow:

**Comment by nunoh** [comment]
I seem to keep having some issue with whitespace stripping in some conditions. For example, if I have the following `status-right` whitespace stripping doesn't occur:

```
set -g status-right '#{battery_icon} #{battery_percentage} #{battery_remain} | %A | %d %h | %H:%M '
```

but if I have the `battery_remain` variable surrounded with `()` it strips off that last whitespace at the end:

```
set -g status-right '#{battery_icon} #{battery_percentage} (#{battery_remain}) | %A | %d %h | %H:%M '
```

I know it's a small thing, but I report it if you want to look into it.

**Comment by bruno-** [comment]
Hmm.. I just tried to reproduce this but no luck. I also surround the `#{battery_remain}` with braces but the whitespace at the right end isn't stripped.

Did you have any new observations around this in the last couple weeks?

**Comment by nunoh** [comment]
Don't seem to have this issue anymore. Could very well have been something else in my configuration, though not sure what that could have been.
