### ISSUE TITLE
Battery percentage not showing in [OS X El Capitan / iTerm 2.1.4 / Tmux 2.1]

### ISSUE THREAD

**Issue by marceloboeira** [tmux-plugins/tmux-battery#21]
I have tried to follow the setup steps, but it seems not to be working on my env.

Here are the versions I am using:
```
OSX El Capitan, 10.11.2
iTerm 2.1.4
Tmux 2.1
```

The final result is that the battery percentage/icon appears for less than a second then disappears. (it just blinks, really)

I've tested with changing the `status-interval` to 10, 15, 60 seconds but it did not change anything.

---

> 2015-01-21

**UPDATE**: If I run, from inside tmux: `run ~/.tmux/plugins/tmux-battery/battery.tmux` it starts working. But I have to run it every time I source the `~/.tmux.conf` file.

**Comment by bruno-** [comment]
I checked your dotfiles and [your setup](https://github.com/marceloboeira/dots/commit/08e009cb7f7d94dde88e3d561d41437aba177d5f) looks ok.

Can you please paste the output of the following command (run it inside tmux with tmux-battery installed):

    tmux show -g status-right

**Comment by marceloboeira** [comment]
@bruno- thanks for the support.

The `status-right` output is:
```bash
"[#(/Users/marceloboeira/.tmux/plugins/tmux-battery/scripts/battery_percentage.sh)][#(hostname -s)][%H:%M]"
```

**Comment by bruno-** [comment]
The output of `status-right` looks good.

I just checked your [tmux.conf](https://github.com/marceloboeira/dots/blob/master/tmux/tmux.conf). And that explains why you're having this issue.

You should source the plugins **last**.
So, put this line

    source "$HOME/.dots/tmux/plugins.tmux"

at the very end of `.tmux.conf` and things should work.

**Comment by marceloboeira** [comment]
@bruno- perfect! That was the problem! Thanks!
