### ISSUE TITLE
Icons are not being displayed anymore on Arch

### ISSUE THREAD

**Issue by oblitum** [tmux-plugins/tmux-battery#23]
Everything used to work until the last batch of updates to Gnome 3.20 that I've applied, now where it was supposed to display the icon and percentage is just blank.

**Comment by bruno-** [comment]
Thanks for reporting. We need someone running linux to help with this.

**Comment by oblitum** [comment]
Hmm, I've just realized that I'm not getting battery feedback not even from gnome menu, this should be particular of my system, unrelated to tmux-battery, sorry for the noise.

**Comment by oblitum** [comment]
I think my issue relates with an update to the kernel: https://bbs.archlinux.org/viewtopic.php?id=211497.

**Comment by oblitum** [comment]
Yes, I'm now using the LTS kernel, this problem is gone.
