### ISSUE TITLE
Using battery Icon

### ISSUE THREAD

**Issue by Thermatix** [tmux-plugins/tmux-battery#26]
I'm not sure if this is a bug or not.
When my mac is charging it displays the lightning bolt icon, when it's full it displays a battery icon, when it's using the battery, it displays nothing, shouldn't there be a 'on battery power' icon?

p.s. this is an awesome plugin, I love having a status bar at the bottom of my terminal, with battery power in it, sooo useful.

**Comment by edouard-lopez** [comment]
see #27

**Comment by martinbeentjes** [comment]
Duplicate of #27.
