### ISSUE TITLE
Battery icon usage inconsistent

### ISSUE THREAD

**Issue by adrianluff** [tmux-plugins/tmux-battery#27]
Using the following config:
```
#tmux.conf
set -g @batt_charged_icon "🔋"
set -g @batt_charging_icon "🔺"
set -g @batt_discharging_icon "🔻"
set -g @batt_attached_icon "🔌"
set -ga status-right #{battery_percentage}#{battery_icon}  #{battery_remain}
```
# Power and icon states observed
Battery full: 🔋
Battery charging: 🔺
Battery discharging: 🔻
Plug attached: <state never used?>

Perhaps I'm misunderstanding the states? At full power you are either attached or have a full battery (for a few minutes anyway!). The attached icon would be used when the battery is full and the power adapter is connected. This doesn't seem to be the case however.

Alternatively the attached state (plug or battery) could optionally be a separate icon from the charging/discharging status indicator.

**Comment by martinbeentjes** [comment]
If you replace the plug for a normal character (e.g. `A`), does it show?

**Comment by adrianluff** [comment]
Nothing shows correctly with MacOS Sierra (10.12):
"(id=4587619)️"

**Comment by martinbeentjes** [comment]
Did you update the plugin, fixes for Sierra were implemented recently. When using tpm, update using  <kbd>CTRL</kbd>+<kbd>b</kbd> followed by <kbd>CTRL</kbd>+<kbd>U</kbd>.

**Comment by adrianluff** [comment]
It's Prefix then U (shift-u) actually. I'd done it a few days ago. I now have the Sierra updated version but it is still not working:
`76%️`
It showed the correct information briefly but now seems to be unhappy.

**Comment by martinbeentjes** [comment]
Okay, so now it shows the battery percentage but not the correct icon?

**Comment by adrianluff** [comment]
The 2-byte Unicode lightning bolt shows up as a question mark, as does the fat battery icon. Same as issue #31 .

**Comment by martinbeentjes** [comment]
And which version of vim are you using? I think this could possibly be a issue regarding to vim itself not understanding the 2-byte Unicode character. I doubt that your terminal itself does not support if the characters/emoticons do show up in the terminal itself. 

I will test the states myself, report back to you if that causes any issue. Could you explain what you mean by: _"The attached icon would be used when the battery is full and the power adapter is connected. This doesn't seem to be the case however."_ ? What do you define as _the case_?

**Comment by adrianluff** [comment]
I was using Vim 7.4 and now Vim 8.0 in MacVim and TUI versions. I'd never seen the plug icon previously but the MacOS Sierra compatible version of tmux-battery shows it now.

**Comment by martinbeentjes** [comment]
Maybe this was an issue regarding Vim 7.4, I search the Vim 8.0 release notes, only interesting thing I found about it: emoji characters are seen as full width characters. And a bit that the emoji are seen as word characters. 

To determine if it is really a Vim problem, and not tmux-battery, it should be reproducible with same configuration as yours.
