### ISSUE TITLE
Time to charge display

### ISSUE THREAD

**Issue by adrianluff** [tmux-plugins/tmux-battery#28]
The Mac calculates the time until the battery is fully charged. It would be useful to display this with the #{battery_remain} flag when the battery is charging rather than showing nothing.

**Comment by martinbeentjes** [comment]
So, if one has the power adapter plugged in: Show the remaining time until full capacity. When the plug is not attached, show how long until battery is empty?

**Comment by adrianluff** [comment]
Yes.

**Comment by martinbeentjes** [comment]
Okay, that sounds good to me. Actual output of all supported commands are needed, will try to get those. And then add this feature in a near future version.

**Comment by rlue** [comment]
Any update on this?
