### ISSUE TITLE
Sierra upgrade broke battery display

### ISSUE THREAD

**Issue by sammilechman** [tmux-plugins/tmux-battery#41]
Hey, I recently upgraded to Sierra and noticed that my tmux battery display broke.

![screen shot 2016-11-03 at 12 15 43 pm](https://cloud.githubusercontent.com/assets/6484380/19981460/4502b208-a1bf-11e6-9c64-f46e162c7f5e.png)

From `~/.tmux.conf`:
```
set -g status-right '#[fg=Cyan]#S #[fg=yellow]#{battery_percentage} #[fg=white]%a %b %d %R'
```

I use tmux plugin manager. Anyone know what's going on here?

**Comment by martinbeentjes** [comment]
Hey! This should be fixed, did you update to the newest version?

**Comment by sammilechman** [comment]
Just updated and now it's fixed. Thanks!

**Comment by EdmundsEcho** [comment]
Thank you. I thought I was updating the plugins when reinstalling them which I had done prior to posting the issue.  I wrongly assumed the links to github in my tmux.conf file would update the plugins before installing.  To the degree I'm not the only one the solution was simple after you pointed the way:  ~/.tmux/plugins/tpm/bin/update_plugins all.

Thank you again for the support and useful plugin. Have a great day.

- E
