### ISSUE TITLE
battery_icon not working

### ISSUE THREAD

**Issue by vass-david** [tmux-plugins/tmux-battery#42]
Instead of battery_icon I see blank space.

Terminal: iTerm2 3.0.1
OS: Mac OS X 10.11.6
TMUX: 2.3

tmux config line:
```
set -g status-right 'Battery: #{battery_icon} #{battery_percentage} (#{battery_remain}) | %a %h-%d %H:%M '
```

I'm not sure if I'm doing something wrong. Everything else I've set up there is working correctly. Is it supported on Mac OS X? I've tried Terminal.app 2.6.1 and the result is same.

**Comment by martinbeentjes** [comment]
Can you provide a screenshot, and did you do anything to the contents of the `@batt_xxx_icon` variables? 

Does your terminal application support the emoji characters?

**Comment by vass-david** [comment]
Ok. I'm an idiot. README says that there is no icon when discharging. Manually setting the icons to custom ones worked perfectly, but then after I removed them realising there should be no icon while discharging, I've removed them but they was still there after sourcing tmux.conf or restarting tmux. So the final solution was to manually add them in config file. BTW there should be a discharging icon anyway. Never-mind. Forget I reported something :D

**Comment by martinbeentjes** [comment]
No problem, I am still thinking of the actual need of the icons.

**Comment by vass-david** [comment]
Well, I've actually got rid of them in the end, since they are really disrupting whole feeling of my cli interface. I've ended up with only textual information instead of icons:
<img width="397" alt="screen shot 2016-11-16 at 13 21 28" src="https://cloud.githubusercontent.com/assets/1549540/20347074/b3c8f2e8-abff-11e6-994c-ced56aff3cb9.png">
With this config:
```
set -g @batt_charged_icon "Charged "
set -g @batt_charging_icon "Charging "
set -g @batt_discharging_icon ""
set -g @batt_attached_icon "Attached but not charging! "

set -g @online_icon "Online"
set -g @offline_icon "Offline"

set -g status-right '#{online_status} | #{battery_icon}#{battery_percentage} (#{battery_remain}) | %a %d %h  %H:%M '
set -g status-right-length 80
```

I've also added spaces after the message "icon", since if it's empty, there is additional space in the bar which really annoyed me.

Now the only thing that bugs me is missing "remaining time" when I'm charging and "calculating remaining time" info when it's calculating after I unplug charger. Is it possible to put it there or can I add it there? I see that the script is really simple.

**Comment by rlue** [comment]
Actually I'd like to chime in and say that having no icon while discharging is not intuitive behavior. 

Personally, I use the following settings:

```
set -g @batt_charged_icon "🔌"
set -g @batt_charging_icon "⚡️"
set -g @batt_discharging_icon "🔋"
```

I think they'd make better defaults, but of course making a change like this would confuse existing users.
