### ISSUE TITLE
Importance of battery icons

### ISSUE THREAD

**Issue by martinbeentjes** [tmux-plugins/tmux-battery#43]
Hey! Thanks for using the plugin, I am currently planning out some future works for this. I would like to receive your feedback on this.

I became the maintainer for this plugins after some contributions to get the plugin working when upgrading to macOS Sierra (`pmset -g batt` output format changed). Thanks to you, we now support ChromeOS. It is also possible to add a changing background color based on the battery percentage. 

But, one of the functionalities is adding emoji characters (two byte unicode characters) based on the status (charging/discharging et cetera). However, I encountered multiple issues regarding this problem. And I have been thinking of the importance of this functionality.

As this is an enhancement to the tmux status bar, I prefer not to use emoji characters. So, personally I do not prefer to use it. 

With this issue, I want to know what you prefer. Should we keep the battery icon, or is it something we could get rid of?

**Comment by forkjoseph** [comment]
Emoji support is super awesome! and should keep the battery icon. However, ChromeOS does not support emoji somehow (yes, it needs more debugging), and I could not use the emoji on my laptop :( 

Could some other chromebook users confirm this??

**Comment by tnguyen14** [comment]
Hi, one remote machines that I have, there's no battery, so the different indicators won't show, which is great. But is there a way I can detect that, so I can change the status accordingly? (for example, remove the separator).

**Comment by martinbeentjes** [comment]
@tnguyen14 Please create an issue for this. Thanks!

**Comment by tnguyen14** [comment]
Done. My apologies for hijacking this issue.

**Comment by rlue** [comment]
Emojis are important to me in that they are an immediately obvious, non-verbal status indicator — it reduces the cognitive load of interpreting their meaning (compared to "charging" vs. "discharging" vs. "charged"). If their functionality could be substituted with something similar, I wouldn't mind having them replaced.

For example, text color would work, but that's already used to indicate current charge state (and is more intuitive for that purpose anyway). Sorry I don't have any better suggestions.
