### ISSUE TITLE
Battery status changes causes incorrect window refresh

### ISSUE THREAD

**Issue by oblitum** [tmux-plugins/tmux-battery#44]
Hi, this is what started to happen on battery status change after some weeks ago. It made me stop using the plugin:

![screenshot from 2016-11-22 12-25-23](https://cloud.githubusercontent.com/assets/1269815/20527367/4842e3e4-b0af-11e6-8e27-76bb1376ade2.png)

When I press Enter after that kind of status change, I get:

![screenshot from 2016-11-22 12-31-19](https://cloud.githubusercontent.com/assets/1269815/20527481/c21a22fe-b0af-11e6-88dc-3b3cdddd24cf.png)

As can be seen, a caret is shown in the left-bottom corner, not the tmux bar, which got hidden bellow the window canvas.

```
~ ❯❯❯ tmux -V
tmux 2.3

~ ❯❯❯ xfce4-terminal --version
Copyright (c) 2003-2016
        The Xfce development team. All rights reserved.
```

**Comment by martinbeentjes** [comment]
Do you use the most recent version of the plugin? What other plugins are you using? Is this issue possibly caused by some other plugin?

**Comment by oblitum** [comment]
OK, just after reporting, it seems I have found the cause... it seems when the battery charging unicode character is `🔋 `, which in my font is like the one in the screenshot, the issue happens. I'm wondering whether this happens because the character is tall.

If I replace the character with another normal one, the issue doesn't happen.

**Comment by martinbeentjes** [comment]
Hmm, interesting case. The icon is a two byte unicode character. Does your terminal support that correctly?

**Comment by oblitum** [comment]
I think yes, I have no issue with unicode, and the other battery full character, which is an unicode one too, doesn't provide the issue.

Answering previous questions, all plugins updates recently and I have bisect that the issue is with the tmux-battery.

**Comment by martinbeentjes** [comment]
Well, I know that in #31 we discovered that two byte unicode characters can have some buggy behavior all the way into libc. I am wondering if the height of an character (more the height of an icon in this case) is the cause of this issue. 

So the character you are using, is causing the terminal (or tmux?) to do a carriage return randomly?

**Comment by oblitum** [comment]
Yes. I'm sorry, I guess it's just an unicode issue now, I have done some more tests and it seems the behavior happens anytime an unicode character gets involved in any of the state changes. What I find strange though is that I've been using this plugin for quite a long time in the same xfce4 terminal emulator and it always worked fine, then one day after an update this stopped behaving well.

**Comment by oblitum** [comment]
I think it's a duplicate of #31.

**Comment by oblitum** [comment]
I think this and #31 should be fixed by now at least on ArchLinux, glibc was just upgraded to 2.26, supporting Unicode 10: https://github.com/tmux/tmux/issues/1057#issuecomment-328294541.
