### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by nerdpad** [tmux-plugins/tmux-battery#48]
I am sure something is wrong with my config. I am very new to shell scripting, and not sure if I am constructing the battery template right.

Can you please take a look at this change set. https://github.com/NerdPad/dotfiles/commit/4b430caca65ff9ed581cbf3b58ba0232b53e8632#diff-e4a99bf3a7fbdabd6456dad3160011e3

I added the following lines to my theme.sh, which is sourced in tmux.config after tmp is loaded.

I am running OSX Sierra

### Theme.sh
```
tm_battery="$battery_icon $battery_percentage $battery_remain"
set -g status-right $tm_tunes' '$tm_battery' '$tm_date' '$tm_host
```

### Tmux Plugin
```
###########################
### Tmux Plugin Manager ###
###########################

# List of plugins
set -g @tpm_plugins '           \
  tmux-plugins/tpm              \
  tmux-plugins/tmux-sensible    \
  tmux-plugins/tmux-resurrect   \
  tmux-plugins/tmux-battery     \
'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
```

### Tmux.conf
```
# load tmux plugin manager
source ~/.dotfiles/tmux/tmux.plugins.sh

#######################
### Color & Style Settings ###
#######################
		 
source ~/.dotfiles/tmux/theme.sh
```

All the plugins are installed.

**Comment by martinbeentjes** [comment]
`tm_battery="$battery_icon $battery_percentage $battery_remain"`

This should be changed to 

tm_battery="#{battery_icon} #{battery_percentage} #{battery_remain}"

**Comment by NerdPad** [comment]
I have tried that but I still don't see any indicator, it's completely empty.

in my tmux.conf I source the plugin.sh before the theme.sh, so the variables should be available, right?

Can those variables be echo'ed in terminal just to check if they are available?

**Comment by martinbeentjes** [comment]
How did you install the plugin? I recommend using [tpm](https://github.com/tmux-plugins/tpm). Follow their README to install tpm. After installing tpm, add `set -g @plugin 'tmux-plugins/tmux-battery` to your tmux configuration file. Source your configuration file, and check if it works now. 

I do not understand what you are doing exactly. Try by doing *exactly* what the README of `tpm` and `tmux-battery` say.

**Comment by NerdPad** [comment]
@martinbeentjes I do have tmp installed, and installed the plugin via tpm (Prefix+I), and I am following the instructions properly, the plugin is also installed.

Instead of adding the plugins in my tmux config, I created another file for them, and I am sourcing that file in my tmux.conf before I source another file (theme.sh) that actually sets the tmux status line.

tmux.plugin.sh (https://github.com/NerdPad/dotfiles/blob/master/tmux/tmux.plugins.sh)
```
###########################
### Tmux Plugin Manager ###
###########################

# List of plugins
set -g @tpm_plugins '           \
  tmux-plugins/tpm              \
  tmux-plugins/tmux-sensible    \
  tmux-plugins/tmux-resurrect   \
  tmux-plugins/tmux-battery     \
'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
```

This file is sourced in my tmux.conf

tmux.conf (https://github.com/NerdPad/dotfiles/blob/master/tmux/tmux.conf.symlink)
```
...
...
# load tmux plugin manager
source ~/.dotfiles/tmux/tmux.plugins.sh

#######################
### Color & Style Settings ###
#######################
		 
source ~/.dotfiles/tmux/theme.sh # this is the last line in my tmux.conf
```

Theme.sh that customizes tmux look. https://github.com/NerdPad/dotfiles/blob/master/tmux/theme.sh

**Comment by martinbeentjes** [comment]
First of all, the use of `@tpm_plugins` is deprecated. Please change this to:

```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-battery'
```

**Comment by fanaugen** [comment]
I have a similar problem: my `.tmux.conf` contains the line

```
set -g status-right "%R | #{battery_icon} #{battery_percentage}"
```

But all I see there is `23:15 |  74%`

The percentage gets updated, which suggests that the plugin works, but no icon is displayed. I tested that the font I use for iTerm *can* display the 🔋  character by hard-coding it.

**Comment by martinbeentjes** [comment]
Hey @nerdpad, can you tell if the above has worked? Do you still have problems?

**Comment by nerdpad** [comment]
@martinbeentjes I have currently stopped using tmux-plugins. Will close the issue for now, will open it later when I test it.
