### ISSUE TITLE
Mac Sierra on MacBook #{battery_percent} #{battery_remain} displays (id: 3997795) ___ 

### ISSUE THREAD

**Issue by EdmundsEcho** [tmux-plugins/tmux-battery#49]
Hi - Thank you for providing and maintaining this plugin.  It's a nice addition to my tmux status. 

Please note that I have updated the plugins and see the battery image icon.  However, the percent remaining displays the id:xxxx and time remaining output is blank.  Is this a formatting issue? Thanks for letting me know if there is anything I can add to the configuration.  -  E

**Comment by sfarzy** [comment]
Please refer to issues #41 and #33. They might help you.

**Comment by martinbeentjes** [comment]
Did #41 and #33 help you?

**Comment by EdmundsEcho** [comment]
Specific instructions on how to upgrade (not just reinstall) the plugins helped. One of those links helped. Thank you. - E

Edmund Cape PhD MBA
917-715-8299
