### ISSUE TITLE
can't show emoticons

### ISSUE THREAD

**Issue by aaronharding** [tmux-plugins/tmux-battery#5]
i was trying to show the :sunglasses: emoticon in my status bar although it's just printing out:

![screen shot 2015-02-11 at 09 59 26](https://cloud.githubusercontent.com/assets/1704000/6144224/0536695c-b1d5-11e4-9dae-ec1f71bec0a4.png)

what can i do?

**Comment by bruno-** [comment]
Hey, try inserting a real emoticon. On a mac you do that by pressing `<cmd> + <ctrl> + <space>` and then choose one.

**Comment by bruno-** [comment]
I think this should work, closing the issue. Please reopen if you still have trouble.

**Comment by aaronharding** [comment]
Yep, this solved it for me. Thanks!
