### ISSUE TITLE
Weird battery value on a desktop computer without battery

### ISSUE THREAD

**Issue by jbleuzen** [tmux-plugins/tmux-battery#55]
I'm running tmux on a debian server `Debian 4.9.13-1 (2017-02-27)` (so there is no battery), and I'm using the latest version of `tmux-battery`…
I have only `#{battery_percentage}` in my status line and it's showing this value : `-2147483647%`

I tried to look into scripts and none of the command used return content (when I enter them manually in a term), I don't know where this value can come from...

Any hint ? Maybe I can hide the `#{battery_percentage}` with a condition ?

**Comment by martinbeentjes** [comment]
Did you update tmux-battery to the latest version?

**Comment by jbleuzen** [comment]
Yes I have !

**Comment by jbleuzen** [comment]
I made a small PR, I don't have a linux laptop to check that it didn't break anything…
But on my server it's fixed with this PR…

**Comment by martinbeentjes** [comment]
Looks good to me, added the PR.

**Comment by jbleuzen** [comment]
Thanks 👍
