### ISSUE TITLE
How to conditionally display battery info

### ISSUE THREAD

**Issue by bcc32** [tmux-plugins/tmux-battery#63]
I have the following snippet in my status-right:

```
#{?#{!=:#{battery_percentage},}, #{battery_status_bg} #{battery_remain} [#{battery_percentage}],}
```

The idea being that I only want to display battery info, etc. if the current machine I'm on actually has a battery. However, when I do have a battery, I get output like `~1:27 []` instead of `~1:27 [22%]` as expected.

Is there a better way to detect the presence/absence of a battery rather than just testing the output of `#{battery_percentage}`?

**Comment by bcc32** [comment]
Appears it has to do with the fact that the variables are interpolated only once. The following patch fixes the issue:

```
diff --git a/battery.tmux b/battery.tmux
index bbed7e4..bccadb2 100755
--- a/battery.tmux
+++ b/battery.tmux
@@ -30,7 +30,7 @@ set_tmux_option() {
 do_interpolation() {
        local all_interpolated="$1"
        for ((i=0; i<${#battery_commands[@]}; i++)); do
-               all_interpolated=${all_interpolated/${battery_interpolation[$i]}/${battery_commands[$i]}}
+               all_interpolated=${all_interpolated//${battery_interpolation[$i]}/${battery_commands[$i]}}
        done
        echo "$all_interpolated"
 }
```

**Comment by martinbeentjes** [comment]
Merged the PR. Thanks for your contribution!
