### ISSUE TITLE
battery_percentage showing wrong value

### ISSUE THREAD

**Issue by s7dhansh** [tmux-plugins/tmux-battery#65]
`upower` has a bug and it shows a wrong info in `energy-full` after resume. For example, it outputs the following on Xubuntu 17.10:
```
 battery
    present:             yes
    rechargeable:        yes
    state:               charging
    warning-level:       none
    energy:              33.9598 Wh
    energy-empty:        0 Wh
    energy-full:         52.9452 Wh
    energy-full-design:  52.9452 Wh
    energy-rate:         22.0185 W
    voltage:             8.398 V
    time to full:        51.7 minutes
    percentage:          75%
    capacity:            85.4978%
    technology:          lithium-polymer
    icon-name:          'battery-full-charging-symbolic'
```

`energy-full` and `energy-full-design` are same despite the `capacity` to be at 85%.

Hence when the script uses these values it yields the wrong percentage.

I was wondering why isn't the `percentage` value being taken directly?

**Comment by martinbeentjes** [comment]
I do not know what made the choice of using this division instead of using the percentage. I do not know if the percentage is always available. If so, we could switch.

On the other hand, you say upower itself has a bug. If that bug get fixed, will our usage be correct?

**Comment by s7dhansh** [comment]
@martinbeentjes screenshot of tmux? What use will that be?
If you need it I can send it, but I will have to re-use your repo. Currently I am using a fork using direct percentage value.

There is a clear discrepancy in both numbers because of the problem mentioned above.

I too do not know if percentage is always available in all distros. I know that it is available through upower from ubuntu repos (all versions post 16.04). You may have to get some community help on other distros.

**Comment by martinbeentjes** [comment]
I am mostly curious as a piece of evidence to show it shows the wrong value. I have no system to test it on right now.

**Comment by sethetter** [comment]
I'm having the same issue. Here's a screenshot.

![image](https://user-images.githubusercontent.com/655500/38285438-c5b388ac-3785-11e8-9ad1-4b5b6f7d7518.png)
