### ISSUE TITLE
Unable to see battery_percentage in status-right

### ISSUE THREAD

**Issue by kdheepak** [tmux-plugins/tmux-battery#81]
Do you know what might be going on here?

<img width="1680" alt="Screen Shot 2019-06-11 at 2 24 48 AM" src="https://user-images.githubusercontent.com/1813121/59256080-6ede8700-8bf0-11e9-817e-241851714581.png">

I'm able to run the script and get the right battery percentage from the command line, but I'm not able to do the same within the tmux status-right.

**Comment by cixel** [comment]
Make sure `run `~/.tmux/plugins/tpm/tpm'` is at the bottom of the file, after `set-option ...`

**Comment by martinbeentjes** [comment]
@kdheepak As @cixel says, please put the `run '~/.tmux/plugins/tpm/tpm'` at the bottom of your tmux configuration file. I will close this issue for now.
