### ISSUE TITLE
Can I use this on WSL?

### ISSUE THREAD

**Issue by rynoV** [tmux-plugins/tmux-battery#86]
I am using Ubuntu installed through the Microsoft Store. Here is my `.tmux.conf`:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g status-right "#{battery_status_bg} #{battery_percentage} #[bg=default,fg=default] #H %d/%m %H:%M"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```
After sourcing with `tmux source ~/.tmux.conf` and installing with `<prefix> I`, the battery info does not show up in my status bar. Could this have something to do with WSL or am I just doing something wrong? Please let me know if you need any more information.

**Comment by rux616** [comment]
I *think* it has something to do with WSL and how it works. IIRC the last time I tested there were a few tmux plugins that weren't working properly. I'll dig into this further when I get a chance (hopefully within a couple weeks).
