### ISSUE TITLE
Is there a way to make the background "transparent" or at least consistently one color?

### ISSUE THREAD

**Issue by jsatk** [tmux-plugins/tmux-battery#93]
Trying to avoid this issue. 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/1005550/78278155-772ee800-74ca-11ea-8bcd-e5db0932bc1b.png">

**Comment by rux616** [comment]
What's your `status-right` tmux option?

**Comment by jsatk** [comment]
@rux616 I ended up figuring out how to resolve this. I set the `bg` right before calling this plugin and it fixed my issue. Thanks.
